name: RPG-0.0.3
main: com.falgael.rpg.RPG
api-version: 1.20
version: 0.0.3
commands:
  experience:
    description: "Manipulate the experience amount of a Player"
    usage: /<command> <modifier> <Proficiency> <amount> [level]
  spawn_chest:
    description: "Spawn a Chest with items of a Proficiency"
    usage: /<command> <Proficiency>
  spawn_spawner:
    description: "Spawn a modified Spawner"
    usage: /<command>
  get:
    description: "gets an item or a group of items"
    usage: /<command> <item|set> <key>
  spawn:
    description: "Spawn a villager with key"
    usage: /<command> <villager> <key>