name: RPG-0.0.1
main: com.falgael.rpg.RPG
api-version: 1.20
version: 0.0.1
commands:
  spawn_villager:
    description: "Spawn a villager with key"
    usage: /<command> <arg>
  experience:
    description: "Manipulate the experience amount of a Player"
    usage: /<command> <Player> <Proficiency> <modifier> <amount>